name: build

on:
  workflow_run:
    workflows: ["prep"]
    types:
      - completed
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  prep:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2
        with:
          always-auth: true
          node-version: '20.x'
          architecture: 'x64'
          check-latest: true
          registry-url: 'https://npm.pkg.github.com/'
          scope: '@pchj'
          token: ${{ secrets.GITHUB_TOKEN }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

  build:
    needs: prep
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run a multi-line script
        run: |
          echo "Add other actions to build,"
          echo "test, and deploy your project."

  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Notebook Analysis
        run: python analyze_notebooks.py
