name: Test

on:
  workflow_run:
    workflows: ["build"]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Updated to v3

      - name: Set up Node.js
        uses: actions/setup-node@v4.0.2
        with:
          always-auth: true
          node-version: '20.x'
          architecture: 'x64'
          check-latest: true
          registry-url: 'https://npm.pkg.github.com/'
          scope: '@pchj'
          token: ${{ secrets.GITHUB_TOKEN }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nbval papermill nbformat nbconvert  # Install nbval, papermill, and other necessary dependencies

      - name: Find Notebook Files
        id: find_notebooks
        run: find . -name "*.ipynb*" ! -name "output_notebook.ipynb" -exec echo {} +

      - name: Analyze Notebooks
        run: python analyze_notebooks.py ${{ steps.find_notebooks.outputs.notebooks }}
